using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright 2014-2015")]
[assembly: AssemblyProductAttribute("Entelect.Encentivize.Sdk")]
[assembly: AssemblyCompanyAttribute("Entelect")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.1.1")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]

