using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright 2012-2015")]
[assembly: AssemblyProductAttribute("Encentivize Sdk")]
[assembly: AssemblyCompanyAttribute("Entelect")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]

